podspec: ChatLayout.podspec
clean: true
author: Evgeny Kazaev
author_url: https://github.com/ekazaev
output: docs
documentation: ./*.md
theme: fullwidth

custom_categories:
  - name: Core
    children:
      - ChatLayout
      - ChatLayoutDelegate
      - ChatLayoutAttributes
      - ChatLayoutSettings
      - ChatLayoutPositionSnapshot
      - ChatLayoutInvalidationContext
      - ItemKind
      - ItemSize

  - name: Extras
    children:
      - ContainerCollectionViewCellDelegate
      - ContainerCollectionReusableView
      - MessageContainerView
      - CellLayoutContainerView
      - EdgeAligningView
      - ImageMaskedView
      - RoundedCornersContainerView
      - StaticViewFactory
      - VoidViewFactory
